version: '2'

catalog:
  name: mail
  version: 0.1
  description: founder-Mail
services:
  mail:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 9025
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
