spring:
  rabbitmq:
    host: rabbitmq.rabbitmq #172.19.58.205 #测试地址
    port: 5672
    username: founder #guest
    password: Founder123 #guest
    publisher-confirms: true
    virtual-host: /
